services:
  nginx:
    container_name: nginx
    build: ./nginx
    image: nginx:v1
    ports:
     - 443:443
    depends_on:
      - wordpress
    volumes:
     - /home/ijaija/data/wp:/var/www/html
    networks:
      - 42-inception
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build: ./wordpress
    image: wordpress:v1
    depends_on:
      - mariadb
    volumes:
      - /home/ijaija/data/wp:/var/www/html
    networks:
      - 42-inception
    env_file:
      - "./.env"
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    build: ./mariadb
    image: mariadb:v1
    volumes:
      - /home/ijaija/data/db:/var/lib/mysql
    networks:
      - 42-inception
    env_file:
      - "./.env"
    restart: unless-stopped

  ftp:
    container_name: ftp
    build: ./ftp
    image: ftp:v1
    network_mode: host
    volumes:
      - /home/ijaija/data/wp:/wp
    env_file:
      - "./.env"
    depends_on:
      - wordpress
    restart: unless-stopped

  redis:
    container_name: redis
    build: ./redis
    image: redis:v1
    depends_on:
      - wordpress
    networks:
      - 42-inception
    restart: unless-stopped
  
  adminer:
    container_name: adminer
    build: ./adminer
    image: adminer:v1
    depends_on:
      - mariadb
    networks:
      - 42-inception
    ports:
      - 8000:8000
    restart: unless-stopped

  prometheus:
    container_name: prom
    build: ./prometheus
    image: prometheus:v1
    depends_on:
      - node-exporter
    extra_hosts:
      - "host-machine:host-gateway"  
    networks:
      - 42-inception
    #ports:
    #  - 9090:9090
    restart: unless-stopped

  node-exporter:
    container_name: node-exporter
    build: ./node-exporter
    image: node-exporter:v1
    network_mode: host
    pid: host
    volumes:
      - /:/host:ro,rslave
    restart: unless-stopped

  grafana:
    container_name: grafana
    build: ./grafana
    image: grafana:v1
    depends_on:
      - prometheus
    networks:
      - 42-inception
    ports:
      - 3000:3000
    restart: unless-stopped

  backups-manager-backend:
    container_name: backups-manager-backend
    build: ./backups-manager/backend
    image: backups-manager-backend:v1
    volumes:
      - /home/ijaija/data/:/volumes
    env_file:
      - "./.env"
    ports:
      - 5000:5000
    networks:
      - 42-inception
    restart: unless-stopped

  backups-manager-frontend:
    container_name: backups-manager-frontend
    build: ./backups-manager/client
    image: backups-manager-frontend:v1
    depends_on:
      - backups-manager-backend
    ports:
      - 3300:3300
    env_file:
      - "./.env"
    networks:
      - 42-inception
    restart: unless-stopped


networks:
  42-inception:
    name: 42-inception


#volumes:
#  wordpress:
#    name: wordpress
#    driver: local
#    driver_opts:
#      device: /home/ijaija/data/wp
#      o: bind
#      type: none
#  mariadb:
#    name: mariadb
#    driver: local
#    driver_opts:
#      device: /home/ijaija/data/db
#      o: bind
#      type: none
